batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 53
model_path: Models/04_sentence_recognition\202403301419
train_epochs: 1000
train_workers: 20
vocab: v*PgGsTZ&'LVpXFna4wh02ei8Qlx/7j?OztBrfo)d.RA!uSC-m:IYD5bENcH"KW,M1yk+q93;#U(6J
width: 1408
