batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202403182310
train_epochs: 1000
train_workers: 20
vocab: )0Repf58kqTcJIS/d+#atUY3!uy'C2ZrX;P:bh&VxF9nHBi?v*"m6W.,(wl4O-NgQDM71GzjosEKAL
width: 128
