batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202403182321
train_epochs: 1000
train_workers: 20
vocab: 3K9tXrj?g/q(JFk6&"m0EznuTw4oYAf;IMi5)O8:PdlV.bHx-RcCB,eDyLs'QNphv1#!2ZaUS7+W*G
width: 128
