batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202403281755
train_epochs: 1000
train_workers: 20
vocab: ',al0b"IwB:i8oPq)#S r.F''CQ!LTXkz?*1GhxpjJs3;U5-v46HM&f2Y/9tydVZ+DcnNmWREKu7Aeg(O'
width: 1408
