batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202403281805
train_epochs: 1000
train_workers: 20
vocab: 2ozli75'JsI;GPxyRBTSAW9Xv-FqVp,Y3)wg(DaK10Zm#HdUe"u/6cbM:Cr!?Qnt4NL*O+Efh.kj
  8&
width: 1408
