batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202403182320
train_epochs: 1000
train_workers: 20
vocab: 8A1N"I,Y43JmqyUSzEC0HGat/5n?;rwhidRWxQ7V!KM:&BXfLZ)ceDv2p9sP*'j(-+lu6kTOb#ogF.
width: 128
