batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202403182319
train_epochs: 1000
train_workers: 20
vocab: p&ZN;6nrFHY')*E7b1DT2XPQLCduy5jI0:OGKa,#.em4W/wkRcixUvSJVB+s-tlh?38"z(!gfqoM9A
width: 128
