batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202403182253
train_epochs: 1000
train_workers: 20
vocab: YgH6'?pZeXtGxnhTMsb.m-j)orI;"WkNDJSU*40&:(KvO#AciLE/+2lwq,zF9a!B5C718VdyufQPR3
width: 128
