batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202403192320
train_epochs: 1000
train_workers: 20
vocab: X#v'LFnw")A-e9?YChUGo:O/T51bWP7tsSdKcg0q(zxiku*yZl4NEHV3;afpm!+MRQI&JB6j,82r.D
width: 128
