batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202403182305
train_epochs: 1000
train_workers: 20
vocab: bsYhJ&'?;Wu2i(AznfOc-yMK.!tQ4Fj/*8)wErlPDRLHNq6d,XpU#"9G0CV53a7:oxTSkg1Bv+emIZ
width: 128
