batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202403182251
train_epochs: 1000
train_workers: 20
vocab: wNXLBb/F:zsnmhK*-iC8ypM+Zv,I;dQ2S3)?4Y9rU5V0(Ot61TjkeoAWlPf'a&xgc!JE.qu"HG7#DR
width: 128
