batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202403182325
train_epochs: 1000
train_workers: 20
vocab: Ngkm:psO7EP5xuK.dVfTSqLW!+FHo8XJ#4j,2zBC0Y-UiI3e'1Z/(;6G*ya?9MhlAtQDvn&rb)cw"R
width: 128
