batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202403230007
train_epochs: 1000
train_workers: 20
vocab: NL"iOQwaGITAWkfE2&Y+edSxH#1CX)q7Bvz-'tKZ4cPb83.*s;9R:r/DJ?u5ygpn,0FUmo(VljMh!6
width: 128
