batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202403182229
train_epochs: 1000
train_workers: 20
vocab: 5K(Z*fah!xg6d;Hw2cuDpGqPkLm7-XTCQjA31NlUoFvE'I?Yn#+"JB.W,0VebMO4itR8)&9:zy/rsS
width: 128
