batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202403281802
train_epochs: 1000
train_workers: 20
vocab: AYVbDKLC;a"e06c9v'z32h&4Fs#k*XW1:r)l57/yMm N!oTP(8wERQx?iutS+-Odp.nUqHgfI,GBJjZ
width: 1408
