batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202403182302
train_epochs: 1000
train_workers: 20
vocab: /EAe.x?UOjg6WR!KTbSJtyiHL5&ozDFZuXk9q17-r,sNp82m(VdcBQ0)Ga;#Ph3+4l'*:"IMCwvYfn
width: 128
