batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 53
model_path: Models/04_sentence_recognition\202403301410
train_epochs: 1000
train_workers: 20
vocab: '!,Y&jhNfKAy"qlCctI-SdkO#ULG.1uB3Pw5(pTo0V8:X9MErZgF*W7eJz;aviHQxm)bs2/n+4R?''D6'
width: 1408
