batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202403281804
train_epochs: 1000
train_workers: 20
vocab: lg"epKiyWFoBb'Mm!hdIX(z;tPqD54)G&6wsxO:Ru,8Cr.7-fj ?+TS23EcaL/UH0YV9AZN1Qn#kJ*v
width: 1408
