batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202403281758
train_epochs: 1000
train_workers: 20
vocab: Ps.'akr8H/eUMhqZw2)(l?V*&,K-C6tFGQ5vymX;"bIjN3!uxS0i cO7AWf4dTYJ:BEpno1R#+gzDL9
width: 1408
